-- MySQL Script generated by MySQL Workbench
-- Wed Nov 19 12:01:41 2014
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Restaurante
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Restaurante` ;

-- -----------------------------------------------------
-- Schema Restaurante
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Restaurante` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `Restaurante` ;

-- -----------------------------------------------------
-- Table `Restaurante`.`mesas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Restaurante`.`mesas` ;

CREATE TABLE IF NOT EXISTS `Restaurante`.`mesas` (
  `idmesa` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  `ocupado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmesa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante`.`orden`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Restaurante`.`orden` ;

CREATE TABLE IF NOT EXISTS `Restaurante`.`orden` (
  `idorden` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `mesas_idmesa` INT NOT NULL,
  `total` INT NULL,
  PRIMARY KEY (`idorden`),
  INDEX `fk_orden_mesas_idx` (`mesas_idmesa` ASC),
  CONSTRAINT `fk_orden_mesas`
    FOREIGN KEY (`mesas_idmesa`)
    REFERENCES `Restaurante`.`mesas` (`idmesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Restaurante`.`categorias` ;

CREATE TABLE IF NOT EXISTS `Restaurante`.`categorias` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante`.`tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Restaurante`.`tipo` ;

CREATE TABLE IF NOT EXISTS `Restaurante`.`tipo` (
  `idtipo` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idtipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Restaurante`.`productos` ;

CREATE TABLE IF NOT EXISTS `Restaurante`.`productos` (
  `idproducto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` INT NOT NULL,
  `disponibilidad` VARCHAR(45) NOT NULL,
  `imagen` VARCHAR(45) NOT NULL,
  `categorias_idcategoria` INT NOT NULL,
  `tipo_idtipo` INT NOT NULL,
  PRIMARY KEY (`idproducto`),
  INDEX `fk_productos_categorias1_idx` (`categorias_idcategoria` ASC),
  INDEX `fk_productos_tipo1_idx` (`tipo_idtipo` ASC),
  CONSTRAINT `fk_productos_categorias1`
    FOREIGN KEY (`categorias_idcategoria`)
    REFERENCES `Restaurante`.`categorias` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_tipo1`
    FOREIGN KEY (`tipo_idtipo`)
    REFERENCES `Restaurante`.`tipo` (`idtipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Restaurante`.`cliente` ;

CREATE TABLE IF NOT EXISTS `Restaurante`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `RFC` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `pApellido` VARCHAR(45) NOT NULL,
  `sApellido` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Restaurante`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `Restaurante`.`usuarios` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(45) NOT NULL,
  `nivel` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante`.`factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Restaurante`.`factura` ;

CREATE TABLE IF NOT EXISTS `Restaurante`.`factura` (
  `idfactura` INT NOT NULL AUTO_INCREMENT,
  `total` INT NOT NULL COMMENT 'total de la factura ya con iva',
  `orden_idorden` INT NOT NULL,
  `cliente_idcliente` INT NOT NULL,
  PRIMARY KEY (`idfactura`),
  INDEX `fk_factura_orden1_idx` (`orden_idorden` ASC),
  INDEX `fk_factura_cliente1_idx` (`cliente_idcliente` ASC),
  CONSTRAINT `fk_factura_orden1`
    FOREIGN KEY (`orden_idorden`)
    REFERENCES `Restaurante`.`orden` (`idorden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `Restaurante`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante`.`carrito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Restaurante`.`carrito` ;

CREATE TABLE IF NOT EXISTS `Restaurante`.`carrito` (
  `orden_idorden` INT NOT NULL,
  `productos_idproducto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio` INT NOT NULL COMMENT 'precio producto * cantidad',
  `edoProdutcto` VARCHAR(45) NOT NULL COMMENT 'servido - enviado ',
  PRIMARY KEY (`orden_idorden`, `productos_idproducto`),
  INDEX `fk_orden_has_productos_productos1_idx` (`productos_idproducto` ASC),
  INDEX `fk_orden_has_productos_orden1_idx` (`orden_idorden` ASC),
  CONSTRAINT `fk_orden_has_productos_orden1`
    FOREIGN KEY (`orden_idorden`)
    REFERENCES `Restaurante`.`orden` (`idorden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orden_has_productos_productos1`
    FOREIGN KEY (`productos_idproducto`)
    REFERENCES `Restaurante`.`productos` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
